language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a 

android:
  components:
    - build-tools-23.0.0
    - android-23
    # Extras
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

  # Enable caching to speed up the build
cache:
  directories:
    - $HOME/.gradle
